"""Financial Model Router public API."""

from fmr.financial_data import (
    CONCEPTS,
    build_binding_profile,
    build_mapping_profile,
    compile_input_set_from_binding_plan,
    concept_registry_payload,
    import_statement_csv,
    map_financial_data,
    plan_financial_input_bindings,
    validate_binding_plan,
    validate_binding_profile,
    validate_financial_data_package,
    validate_mapping_profile,
    validate_mapping_result,
)
from fmr.plan import build_plan
from fmr.core import FAMILIES, ModelJob, create_model_intent, create_scope_assessment, create_scope_candidate, create_scope_confirmation, route_job, routing_policy, validate_model_intent, validate_scope_assessment, validate_scope_candidate, validate_scope_confirmation
from fmr.core.receipts import validate_execution_result, validate_provider_handoff, validate_route_decision
from fmr.execution import (
    EnvironmentSecretResolver,
    ExecutionOrchestrator,
    ExecutionRequest,
    ManagedArtifactRetention,
    SqliteExecutionLedger,
)
from fmr.provider_service import prepare_handoff
from fmr.registry import ProviderRegistry
from fmr.vocabulary import VocabularyRegistry
from fmr.organization import OrganizationPolicy, route_organization_job
from fmr.qualification import qualify_local_release, validate_deployment_evidence
from fmr.acceptance import run_acceptance_corpus, validate_acceptance_corpus
from fmr.router import route_request
from fmr.providers.native_xlsx.workbook import (
    accept_calculated_workbook_bytes,
    analyse_workbook_map,
    calculate_and_accept_workbook_bytes,
    calculate_and_accept_workbook_file,
    calculation_engine_status,
    compile_workbook_input_set_from_csv,
    compile_workbook_patch,
    compile_workbook_write_plan,
    content_spec_registry_payload,
    coordinate_rule_registry_payload,
    derive_workbook_evidence,
    discover_calculation_engine,
    execute_workbook_write_plan_bytes,
    execute_workbook_write_plan_file,
    formula_spec_registry_payload,
    inspect_workbook,
    inspect_workbook_bytes,
    operation_spec_registry_payload,
    plan_workbook_content,
    plan_workbook_coordinates,
    plan_workbook_realization,
    populate_workbook_inputs_bytes,
    populate_workbook_inputs_file,
    resolve_workbook_patch_targets,
    style_spec_registry_payload,
    validate_input_population_calculation_link,
    validate_workbook_calculation_acceptance_payload,
    validate_workbook_content_plan_payload,
    validate_workbook_coordinate_plan_payload,
    validate_workbook_execution_receipt_payload,
    validate_workbook_input_population_receipt_payload,
    validate_workbook_input_set_payload,
    validate_workbook_patch_payload,
    validate_workbook_patch_receipt_payload,
    validate_workbook_realization_plan_payload,
    validate_workbook_target_resolution_payload,
    validate_workbook_write_context_payload,
    validate_workbook_write_plan_payload,
)

__all__ = [
    "FAMILIES",
    "ExecutionOrchestrator",
    "ExecutionRequest",
    "EnvironmentSecretResolver",
    "ManagedArtifactRetention",
    "SqliteExecutionLedger",
    "ModelJob",
    "ProviderRegistry",
    "VocabularyRegistry",
    "OrganizationPolicy",
    "qualify_local_release",
    "run_acceptance_corpus",
    "CONCEPTS",
    "accept_calculated_workbook_bytes",
    "analyse_workbook_map",
    "build_binding_profile",
    "build_mapping_profile",
    "build_plan",
    "calculate_and_accept_workbook_bytes",
    "calculate_and_accept_workbook_file",
    "calculation_engine_status",
    "compile_input_set_from_binding_plan",
    "compile_workbook_input_set_from_csv",
    "compile_workbook_patch",
    "compile_workbook_write_plan",
    "create_model_intent",
    "create_scope_assessment",
    "create_scope_candidate",
    "create_scope_confirmation",
    "concept_registry_payload",
    "content_spec_registry_payload",
    "coordinate_rule_registry_payload",
    "derive_workbook_evidence",
    "discover_calculation_engine",
    "execute_workbook_write_plan_bytes",
    "execute_workbook_write_plan_file",
    "formula_spec_registry_payload",
    "import_statement_csv",
    "inspect_workbook",
    "inspect_workbook_bytes",
    "map_financial_data",
    "operation_spec_registry_payload",
    "plan_financial_input_bindings",
    "plan_workbook_content",
    "plan_workbook_coordinates",
    "plan_workbook_realization",
    "populate_workbook_inputs_bytes",
    "populate_workbook_inputs_file",
    "resolve_workbook_patch_targets",
    "route_request",
    "route_job",
    "route_organization_job",
    "routing_policy",
    "prepare_handoff",
    "style_spec_registry_payload",
    "validate_binding_plan",
    "validate_binding_profile",
    "validate_financial_data_package",
    "validate_input_population_calculation_link",
    "validate_mapping_profile",
    "validate_mapping_result",
    "validate_model_intent",
    "validate_scope_assessment",
    "validate_scope_candidate",
    "validate_scope_confirmation",
    "validate_workbook_calculation_acceptance_payload",
    "validate_workbook_content_plan_payload",
    "validate_workbook_coordinate_plan_payload",
    "validate_workbook_execution_receipt_payload",
    "validate_workbook_input_population_receipt_payload",
    "validate_workbook_input_set_payload",
    "validate_workbook_patch_payload",
    "validate_workbook_patch_receipt_payload",
    "validate_workbook_realization_plan_payload",
    "validate_workbook_target_resolution_payload",
    "validate_workbook_write_context_payload",
    "validate_workbook_write_plan_payload",
    "validate_execution_result",
    "validate_provider_handoff",
    "validate_deployment_evidence",
    "validate_acceptance_corpus",
    "validate_route_decision",
]
__version__ = "1.0.0a1"
