"""Financial Model Router public API."""

from fmr.plan import build_plan
from fmr.router import route_request
from fmr.workbook import (
    accept_calculated_workbook_bytes,
    analyse_workbook_map,
    calculate_and_accept_workbook_bytes,
    calculate_and_accept_workbook_file,
    calculation_engine_status,
    compile_workbook_input_set_from_csv,
    compile_workbook_patch,
    compile_workbook_write_plan,
    content_spec_registry_payload,
    coordinate_rule_registry_payload,
    derive_workbook_evidence,
    discover_calculation_engine,
    execute_workbook_write_plan_bytes,
    execute_workbook_write_plan_file,
    formula_spec_registry_payload,
    inspect_workbook,
    inspect_workbook_bytes,
    operation_spec_registry_payload,
    plan_workbook_content,
    plan_workbook_coordinates,
    plan_workbook_realization,
    populate_workbook_inputs_bytes,
    populate_workbook_inputs_file,
    resolve_workbook_patch_targets,
    style_spec_registry_payload,
    validate_input_population_calculation_link,
    validate_workbook_calculation_acceptance_payload,
    validate_workbook_content_plan_payload,
    validate_workbook_coordinate_plan_payload,
    validate_workbook_execution_receipt_payload,
    validate_workbook_input_population_receipt_payload,
    validate_workbook_input_set_payload,
    validate_workbook_patch_payload,
    validate_workbook_patch_receipt_payload,
    validate_workbook_realization_plan_payload,
    validate_workbook_target_resolution_payload,
    validate_workbook_write_context_payload,
    validate_workbook_write_plan_payload,
)

__all__ = [
    "accept_calculated_workbook_bytes",
    "analyse_workbook_map",
    "build_plan",
    "calculate_and_accept_workbook_bytes",
    "calculate_and_accept_workbook_file",
    "calculation_engine_status",
    "compile_workbook_input_set_from_csv",
    "compile_workbook_patch",
    "compile_workbook_write_plan",
    "content_spec_registry_payload",
    "coordinate_rule_registry_payload",
    "derive_workbook_evidence",
    "discover_calculation_engine",
    "execute_workbook_write_plan_bytes",
    "execute_workbook_write_plan_file",
    "formula_spec_registry_payload",
    "inspect_workbook",
    "inspect_workbook_bytes",
    "operation_spec_registry_payload",
    "plan_workbook_content",
    "plan_workbook_coordinates",
    "plan_workbook_realization",
    "populate_workbook_inputs_bytes",
    "populate_workbook_inputs_file",
    "resolve_workbook_patch_targets",
    "route_request",
    "style_spec_registry_payload",
    "validate_input_population_calculation_link",
    "validate_workbook_calculation_acceptance_payload",
    "validate_workbook_content_plan_payload",
    "validate_workbook_coordinate_plan_payload",
    "validate_workbook_execution_receipt_payload",
    "validate_workbook_input_population_receipt_payload",
    "validate_workbook_input_set_payload",
    "validate_workbook_patch_payload",
    "validate_workbook_patch_receipt_payload",
    "validate_workbook_realization_plan_payload",
    "validate_workbook_target_resolution_payload",
    "validate_workbook_write_context_payload",
    "validate_workbook_write_plan_payload",
]
__version__ = "0.4.2"
